name: 📦 Unity CD

# on:
#   pull_request: {}
#   push: { branches: [master, development] }

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  readmeWorkflow:
    name: Unity Build Workflow ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: BunnyHopMaster
          unityVersion: 2019.3.9f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: BunnyHopMaster
          unityVersion: 2019.3.9f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

