name: 🧪 Unity CI

# on:
#   pull_request: {}
#   push: { branches: [master] }

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  readmeWorkflow:
    name: Unity Test Workflow ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
#      # Cache
#      - uses: actions/cache@v1.1.0
#        with:
#          path: test-project/Library
#          key: Library-test-project-WebGL

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: BunnyHopMaster
          unityVersion: 2019.3.9f1

